## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split, KFold

In [13]:
y_class1 = y[np.where(y==1)]
y_class2 = y[np.where(y==0)]

x_class1 = X[np.where(y==1)]
x_class2 = X[np.where(y==0)]

In [20]:
x_class1_train, x_class1_test, y_class1_train, y_class1_test = train_test_split(x_class1, y_class1, test_size=0.25, random_state=42)
x_class2_train, x_class2_test, y_class2_train, y_class2_test = train_test_split(x_class2, y_class2, test_size=0.0625, random_state=43)

x_train = np.append(x_class1_train,x_class2_train,axis = 0)
y_train = np.append(y_class1_train,y_class2_train)

x_test = np.append(x_class1_test,x_class2_test,axis = 0)
y_test = np.append(y_class1_test,y_class2_test)

print(x_test)
print(y_test)

[[ 95  96  97  98  99]
 [ 80  81  82  83  84]
 [ 75  76  77  78  79]
 [130 131 132 133 134]
 [ 20  21  22  23  24]
 [ 60  61  62  63  64]
 [185 186 187 188 189]
 [135 136 137 138 139]
 [195 196 197 198 199]
 [ 30  31  32  33  34]
 [295 296 297 298 299]
 [555 556 557 558 559]
 [395 396 397 398 399]
 [795 796 797 798 799]
 [200 201 202 203 204]
 [700 701 702 703 704]
 [960 961 962 963 964]
 [385 386 387 388 389]
 [525 526 527 528 529]
 [830 831 832 833 834]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
